name: Documentation improvement
description: Report an issue with the documentation.
labels: [documentation]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have checked that this documentation improvement has not already been requested.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the issue with the documentation and how it can be fixed or improved.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: >
        Provide a link to the existing documentation, if applicable.
      placeholder: ex. https://pyticktick.pretzer.io/...
    validations:
      required: false
