name: Feature request
description: Suggest a new feature or enhancement for pyticktick.
labels: [enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have checked that this feature has not already been requested.
          required: true
        - label: I have confirmed this feature does not exist on the [latest version](https://pypi.org/project/pyticktick/) of pyticktick or in the [repository](https://github.com/sebpretzer/pyticktick).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Describe the feature or enhancement and explain why it should be implemented.
        Include a (pseudo)code example if possible. If this is to support a specific API endpoint, provide details about the endpoint and its expected behavior.
    validations:
      required: true
